version: '3.7'

services:

  client:
    container_name: frontend
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true yarn start
    # command: /app/bootup.sh ${SSL_ON}